# 开发环境配置
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop  # 开发环境重新创建表结构
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # 添加连接池配置
        connection:
          provider_disables_autocommit: true

# 文件上传配置 - 开发环境使用本地路径
app:
  file-upload:
    image-base-path: /home/ubuntu/app/server/images
#    image-base-path: C:/Users/15153/Desktop/test/uploads
    goods-image-path: goods
    allowed-image-types: jpg,jpeg,png,gif,webp
    max-file-size: 10
    image-quality: 85
    thumbnail-size: 200

# 日志配置 - 开发环境更详细的日志
logging:
  level:
    com.tk.cratemanagement: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.orm.jpa: DEBUG